app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get '', to: 'fe/homepage#index'

  as :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy'
  end

  namespace :app do
    namespace :listings do
      get '', action: 'index', as: ''
      get ':id', action: 'show', as: 'show'
      get ':id/reviews', action: 'reviews', as: 'reviews'
      post '', action: 'create', as: 'create'
    end
  end
end

app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  # @TODO add URL validation
end

app/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :listing
end

app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :listings, dependent: :destroy
end

app/app/controllers/app/listings_controller.rb
module App
  class ListingsController < ApplicationController
    before_action :authenticate_user!

    def index
      @listings = Listings::Find.find_all({ id: params[:id], current_user: })
    end

    def show
      @listing = Listings::Find.find_one_by_id({ id: params[:id], current_user: })
      raise ActionController::RoutingError, 'Not Found' unless @listing.present?
    end

    def reviews
      @listing = Listings::Find.find_one_by_id({ id: params[:id], current_user: })
      raise ActionController::RoutingError, 'Not Found' unless @listing.present?

      render json: Listings::Reviews.call({ listing: @listing, current_user: })
    end

    def create
      listing = ::Listings::Create.call({ current_user:, url: params[:listing][:url] })

      redirect_to app_listings_show_path(id: listing.id)
    end
  end
end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    app_listings_path
  end
end

app/app/controllers/fe/homepage_controller.rb
module Fe
  class HomepageController < ApplicationController
    def index; end
  end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
end

app/app/views/app/listings/index.html.erb
<h1>Your Listings</h1>

<%= form_for :listing, url: app_listings_create_path do |f| %>
  <%= f.label :url, "Add new listing from Airbnb URL:" %>
  <%= f.text_field :url %>
  <%= f.submit "Submit" %>
  <br>
  <p>example url: https://www.airbnb.com/h/roofdeckhottub</p>
<% end %>

<ul>
    <% @listings.each do |listing| %>
        <li>
            <%= link_to listing.title, app_listings_show_path(id: listing.id) %>
        </li>
    <% end %>
</ul>

app/app/views/app/listings/show.html.erb
<h1><%= @listing.title %></h1>

<div data-controller="data" data-data-url-value="<%= app_listings_reviews_path %>">
  <p>If you just created this listing, give it a few seconds and hit refresh button below to display the data.</p>
  <button data-action="click->data#connect">Refresh</button>
</div>

<div>
  <canvas id="month-chart" width="800" height="200"></canvas>
  <canvas id="year-chart" width="800" height="200"></canvas>
  <canvas id="wordcloud" width="800" height="200"></canvas>
</div>

app/app/views/fe/homepage/index.html.erb
<h1>Welcome to Rails Playground</h1>

<% if !!current_user %>
    <p>Go to <%= link_to 'Your Listings', :app_listings %> or <%= link_to 'Logout', :logout %>.</p>
<% else %>
    <p><%= link_to 'Sign in', :sign_in %> to continue.</p>
<% end %>

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wordcloud2.js/1.0.1/wordcloud2.min.js" integrity="sha512-V9GoXkVO7MfITOYkagdEaqowj4FJtxO7SLhX38OHNBCDnQOGeNiFVveH/hGXWvWVEp7UhAXIa3mDsn6APywNvg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <%= yield %>
  </body>
</html>